services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    ports:
      - "2376:2376"
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      jenkins:
        aliases:
          - docker
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_TLS_VERIFY=1
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
    depends_on:
      jenkins-docker:
        condition: service_started
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
volumes:
  jenkins-data:
  jenkins-docker-certs:
networks:
  jenkins:
    external: true
