pipeline {
    agent any
    tools {
        maven "maven"
        allure "allure"
    }
    stages {
        stage('Cleanup Workspace') {
            steps {
                deleteDir()
            }
        }
        stage('Clone project') {
            steps {
                git branch: 'develop', url: 'https://github.com/Ruslan-Bikineev/Project.git'
            }
        }
        stage('Build and Run API Tests') {
            steps {
                sh 'docker build -t api-tests-image .'
                sh 'mkdir -p target/allure-results'
                sh 'docker run --rm -d --name api-tests-container --mount type=bind,source="$(pwd)/target",destination=/app/target api-tests-image'
                sh 'docker wait api-tests-container'
                sh 'docker rmi api-tests-image'
            }
        }
    }
    post {
        always {
            // Генерация отчета Allure
            sh 'allure generate --single-file target/allure-results'
            // Отправка отчета по электронной почте
            emailext attachLog: true, attachmentsPattern: 'allure-report/*.html',
                body: '',
                subject: 'Jenkinks Report ${env.JOB_NAME} ${env.BUILD_NUMBER}',
                to: 'biken_r@mail.ru'
            // Генерация и сохранение отчета Allure в Jenkins
            allure includeProperties: false, jdk: '', results: [[path: 'target/allure-results']]
        }
    }
}