pipeline {
    agent any
    tools {
        maven "maven"
    }
    stages {
        stage('Clone project') {
            steps {
                git branch: 'develop', url: 'https://github.com/Ruslan-Bikineev/Project.git'
            }
        }
        stage('Build docker images and run tests') {
            steps {
                sh 'docker build -t api-tests-image .'
                sh 'mkdir -p target/allure-results'
                sh 'docker run --rm -d --name api-tests-container --mount type=bind,source="$(pwd)/target",destination=/app/target --user jenkins api-tests-image'
                sh 'docker wait api-tests-container'
                sh 'docker rmi api-tests-image'
            }
        }
    }
    post {
        always {
            // Генерация отчета Allure
            allure includeProperties: false, jdk: '', results: [[path: 'target/allure-results']]
            // Очистка рабочего пространства
            deleteDir()
        }
    }
}