pipeline {
    agent any
    tools {
        maven "maven"
        allure "allure"
    }
    stages {
        stage('Cleanup Workspace') {
            steps {
                deleteDir()
            }
        }
        stage('Clone project') {
            steps {
                git branch: 'branch of git repository', url: 'https git repository url'
            }
        }
        stage('Build and Run API Tests') {
            steps {
                sh 'docker build -t api-tests-image .'
                sh 'mkdir -p target/allure-results'
                sh 'docker run --rm -d --name api-tests-container --mount type=bind,source="$(pwd)/target",destination=/app/target api-tests-image'
                sh 'docker wait api-tests-container'
                sh 'docker rmi api-tests-image'
            }
        }
        stage('Generate allure report') {
            steps {
                // Генерация отчета Allure в 1 файл
                sh 'mvn allure:report'
                // Генерация и сохранение отчета Allure в Jenkins
                allure includeProperties: false, jdk: '', results: [[path: 'target/allure-results']]
            }
        }
    }
    post {
        always {
            // Отправка отчета по электронной почте
            emailext attachLog: true, attachmentsPattern: 'target/site/allure-maven-plugin/index.html',
                body: '',
                subject: "Jenkins Report: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                to: 'your email address'
        }
    }
}